image:
  repository: localhost:5001/kreator-frontend
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  port: 80

ingress:
  enabled: true
  className: nginx
  host: frontend.localhost

env:
  NEXT_PUBLIC_API_URL: http://api.localhost

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop: ["ALL"]
