---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secrets
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgDoWXM93zit+D28oE2DJkoZMi7MRzE171TvmMA8Jc8FL4+zUCatKrzgz870/0PY+HTKv/0WNnQ4cDnmuoaF6pYUfGtMHXNw9Gkd6SUYswku6LNMKa2cXqtuk2+xCLGaCcTa9yaAUTNXfN/yxVxojZ64tk7nR65Qh6xGc1KdeI6HAp2GDq+ZhvvQAK7IvBl1VCyOx2Mdc9XFPl6aj6F1Lw49t5mQwJhXESL1Q2Gx7znayP87fByt3e2yIsDaeWjVFWYG+s+uU3xZBNG21QtGff2yyChjr+htPcSCw3oRB9FUtZLcou0uPQ0T8jyKXu16OGMJVLqspnOB7pGnGPD7uY+eXHr6N2Tb1HZHaz399/xn8N1KPEOPZVTFE2V0Pd4TbFaavoUE+Kd6yVacuAQ37K2n0ADm25opX0WwUloDsOwj6gZIhwzdgp+bL8s0j0+eOqkBEsNvlieFx/o/2P+OWSgi8lSpjmH0cWWZKx+wkwxLW3g7lW9Rlm5315HP7LAYDdNQT34UleWEDfwMP9s9sjefsx/a/fAgY31knTe/4Yzfje1S4w+mlKdnzF4qYlVjcDQrPm0HK3CKAE+6VhY8md3tQjSoueRwUXielBqrnSaT2VUBMT07aHYsboWtFnW8IlH12TEFHLr3eg19gOk8aBhU1N3HkcZEnYZ3ijZcg+o4K6BE879k1ygW7TE1e48cFdcmIGKtR+T+EXQMDx+X7top2yA1k936E7kgI6TW0fhClaIj+iujq4pgMfLEe48MykE+VAgLNhf8IYfstAPXgXT0Cr66xonX33KqAb5lcJBwCXrT4vVirN35OPcFot8YdRrJdbnlCbfPIu3pPwmyc3RB
  template:
    metadata:
      name: backend-secrets
      namespace: default
